Auto-discovery fails on Laravel 5.5 due to incorrect path
Path is wrong, so the service provider fails.

```php
Fatal error: Illuminate\Support\ServiceProvider::loadRoutesFrom(): Failed opening required '/project/path/vendor/rachidlaasri/laravel-installer/src/Providers/../routes/web.php' (include_path='.:/home/travis/.phpenv/versions/7.0.22/share/pear') in /project/path/vendor/laravel/framework/src/Illuminate/Support/ServiceProvider.php on line 71
```